[LOOK]
min = 0
max = 360
width = 1
step = 1

[DEPRESSION]
center = -7.5, 2.5
width = 5

[ALGORITHM]
significance_level = 0.05
# Coverage factor `k` is used in calculating the lower and upper fences for IQR outlier removal
coverage_factor = 3
bootstrap_iterations = 1000
